#!/bin/bash
match=0

if [[ "$1" == "Yes" ]]; then
    FILTER="-vf edgedetect,colorchannelmixer=0:0:0:0:1:1:1:0:0:0:0:0"
else
    FILTER=""
fi

echo "$2" >> logs/video-history.log

# Fix up missing protocols
if [[ "$2" == https://* ]] || [[ "$2" == http://* ]] || [[ "$2" == rtsp://* ]]; then
	VIDEO="$2"
else
	VIDEO="https://$2"
fi

while read line; do
	case "$VIDEO" in "$line"*)
		match=1
		break
	esac
done < config/stream-whitelist

if [ "$match" -eq 0 ]; then
	xecho -no-stdin -fc red -bc black -maxsize 100 "URL not whitelisted"
	exit 1
fi

xecho -no-stdin -fc red -bc black -maxsize 100 "Please wait..." &
VIDEO=$(~/youtube-dl/youtube-dl -g -f best "$VIDEO")
mpv --input-file=control/$LOCATION-mpv --include=config/mpv/$LOCATION $FILTER "$VIDEO"
kill $(jobs -p)
